id: 18f4ff11-b758-4bf2-9a37-719a22f5a4b8
name: couchbase
language: PYTHON27
hostTypes:
- UNIX
pluginType: STAGED
entryPoint: plugin_runner:plugin
srcDir: src
schemaFile: schema.json
externalVersion: 1.0.0
buildNumber: 1.0.0
