site_name: Couchbase Plugin
theme:
  name: material
  custom_dir: 'material/'
  palette:
    primary:
    accent:
  logo: 'image/delphix-logo-white.png'
  favicon: 'image/logo.png'
  font:
    text: Helvetica Neue
    code: Ubuntu Mono

copyright: Copyright &copy; 2020 Delphix Corp.

google_analytics:
  - 'UA-35429885-3'
  - 'auto'

repo_url: https://github.com/delphix/couchbase-plugin
repo_name: Github
use_directory_urls: false
pages:
  - Overview: 'index.md'
  - Installation: 'Installation.md'
  - PluginDevelopment : 'PluginDevelopment.md'
  - Discovery: 'Discovery.md'
  - Linking: 'Linking.md'
  - Provisioning: 'Provisioning.md'

extra:
  social:
    - type: sitemap
      link: https://www.delphix.com/
    - type: facebook
      link: https://www.facebook.com/DelphixCorp/
    - type: twitter
      link: https://twitter.com/delphix
    - type: linkedin
      link: https://www.linkedin.com/company/delphix
    - type: github
      link: https://github.com/delphix

extra_css:
  - 'stylesheets/extra.css'

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite:
      guess_lang: false
  - meta

plugins:
  - search
